[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
hello_anchor = "HzsrsmTepXZRCSc4jcUAdbPzLEmPAG9shr8DSzpGPbgp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = 'C:\Users\chera\.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
